### ISSUE TITLE
Some Many Tricks Sparkle URLs

### ISSUE THREAD

**Issue by petermaurer** [tjluoma/di#1]
Not sure which ones you already have, so here's all of them:

Butler: https://manytricks.com/butler/butlercast.xml
Desktop Curtain: https://manytricks.com/desktopcurtain/appcast.xml
Key Codes: https://manytricks.com/keycodes/appcast.xml
Keymo: https://manytricks.com/keymo/appcast.xml
Leech: https://manytricks.com/leech/appcast.xml
Moom: https://manytricks.com/moom/appcast.xml
Name Mangler: https://manytricks.com/namemangler/appcast.xml
Resolutionator: https://manytricks.com/resolutionator/appcast.xml
Time Sink: https://manytricks.com/timesink/appcast.xml
Usher: https://manytricks.com/usher/appcast.xml
Witch: https://manytricks.com/witch/appcast.xml

**Comment by tjluoma** [comment]
All Many Tricks apps now have scripts in the repo. Thanks for the feeds!
