### ISSUE TITLE
Marked and Marked2 scripts refer to the same application

### ISSUE THREAD

**Issue by galli-a** [tjluoma/di#10]
Both scripts refer to the same application. Using the automation, both scripts are run all the times. Obviously not a big issue, since the second one to be run will see the updated version installed by the first one, but shouldn't the Marked script refer to version 1 and the Marked2 script refer to version 2?

**Comment by tjluoma** [comment]
That’s a bug. I meant to delete the “marked2” version. There’s 
no reason to check for updates with Marked 1.

**Comment by tjluoma** [comment]
Fixed 2016-05-26
