### ISSUE TITLE
Add Soundnode

### ISSUE THREAD

**Issue by emilstahl** [tjluoma/di#13]
Hi

Can you add [Soundnode](http://www.soundnodeapp.com)? 

https://api.github.com/repos/Soundnode/soundnode-app/releases

**Comment by tjluoma** [comment]
Not unless there’s a pre-compiled app that goes along with each release.

**Comment by emilstahl** [comment]
There is this http://www.soundnodeapp.com/downloads/mac/Soundnode-App.zip, which must be the latest release.

**Comment by tjluoma** [comment]
Added Soundnode today.

**Comment by tjluoma** [comment]
Soundnode now available at https://github.com/tjluoma/di/blob/master/di-soundnode.sh
