### ISSUE TITLE
Hazel Changed Sparkle feed URL

### ISSUE THREAD

**Issue by benhager** [tjluoma/di#2]
The Sparkle feed URL in the current scripts is: http://update.noodlesoft.com/Products/Hazel/appcast.php?version=$INSTALLED_VERSION

That feed no longer works, I did some digging and it appears the new URL is:  https://www.noodlesoft.com/Products/Hazel/generate-appcast.php?version=$INSTALLED_VERSION

I did some testing of this and updated my version of Hazel from Version 4.0 to 4.0.1 using the new URL without issue.

Thanks for all your doing, this is a great project!!

**Comment by tjluoma** [comment]
Thanks! I updated `di-hazel` with this
