### ISSUE TITLE
di-auto.sh does not detect Hazel

### ISSUE THREAD

**Issue by galli-a** [tjluoma/di#22]
The title says it all

**Comment by superbimble** [comment]
Thanks for the prod. 
I was aware that I need to add a specific catch for Hazel (and I'm pretty sure I need to fix evernote as well) but hadn't got round to it yet.  I'll take a look.

Cheers

**Comment by tjluoma** [comment]
FWIW - I've recently revived this project (sorry, the past two years have been… well, a lot).

All of the scripts now use INSTALL_TO and none of them use APPNAME anymore, which should make it easier to fix `di-auto.sh`.

**Comment by tjluoma** [comment]
I think I've solved this, now that I understand [di-auto.sh](https://github.com/tjluoma/di/blob/master/di-auto.sh) a little better.

This commit shows the major changes:

https://github.com/tjluoma/di/commit/5fa9cbfcbbbbb291d097d59eb284bb424c08509a

If it's not working for some reason, please open another issue and explain what isn't working properly.
