### ISSUE TITLE
Add apps

### ISSUE THREAD

**Issue by emilstahl** [tjluoma/di#23]
### Cyberduck

Release/stable: `https://version.cyberduck.io/changelog.rss`
Beta: `https://version.cyberduck.io/beta/changelog.rss`
Snapshot build/nightly: `https://version.cyberduck.io/nightly/changelog.rss`
### BitTorrent Sync

`https://update.getsync.com/cfu.php?forced=1&b=sync&lang=en&pl=mac&sysver=10.12.0&v=33751046`

**Comment by tjluoma** [comment]
Both are now included!
